Feat/user consent
smileidentity/Smile_ID_Android_Sample pull request #15
Opened 2021-07-12 13:42 UTC by ArlonTM

- User consent screens
- Consent submission routine
- Code cleanup

2021-07-13 12:02 UTC, JNdhlovu requested changes
Major concern here is the smile_config.json please make sure it's not committed

2021-07-13 12:02 UTC, JNdhlovu commented on app/build.gradle
> +            minifyEnabled false
please turn this on

2021-07-13 12:02 UTC, JNdhlovu commented on app/build.gradle
> +        pickFirst 'lib/armeabi-v7a/libopencv_coresid.so'
Why do we need this? did some work to make sure this wasn't the case, what's breaking here?

2021-07-13 12:02 UTC, JNdhlovu commented on app/smile_config.json
> -  "auth_token": "gNra9o0gy3pRFg0xc3NXZwAYtAPj1L9iOIQjX3yK0Ui2QG1lZ68VcNNfs34QW1h5Wg+PTe2UCZUjLpK5VNjwmU2I94Ihdjb9HplUODatu5QuThDmg+w7kd5PZrkXXI79xRRD6d9b7oqefA07rj3GoMFZ2YCDNN50EMPIgSdWSnw=",
Please remove this from the sample app and from the history, sharing this information is a big big risk this is a public repository

2021-07-13 12:02 UTC, JNdhlovu commented on app/src/main/java/com/demo/smileid/sid_sdk/BaseSIDActivity.java
> +        //Partner's name shouldn't be hardcoded
This needs to be tied to the job by using the tag

2021-07-21 11:35 UTC, ArlonTM commented on app/smile_config.json
> -  "auth_token": "gNra9o0gy3pRFg0xc3NXZwAYtAPj1L9iOIQjX3yK0Ui2QG1lZ68VcNNfs34QW1h5Wg+PTe2UCZUjLpK5VNjwmU2I94Ihdjb9HplUODatu5QuThDmg+w7kd5PZrkXXI79xRRD6d9b7oqefA07rj3GoMFZ2YCDNN50EMPIgSdWSnw=",
Totally agree! Currently devising a workaround that would make this data available to Bitrise without exposing it in this repo. This information is important to run the application successfully.

2021-07-21 11:35 UTC, ArlonTM commented on app/build.gradle
> +            minifyEnabled false
This is only for Bitrise; there is an issue minifying code and applying **_proguard_** rules. Once approved this will be reverted.

2022-01-26 11:56 UTC, merged